### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-tomo3d#22]
These tests fail despite everything seems to work (the asset is probably too strict)
```
$ scipion3 tests tomo3d.tests.test_protocol_reconstruct_tomogram
Scipion v3.0.12 - Eugenius
Running tests....
Creating project at /media/SharedDisk/ScipionProjects/projects/TestTomogramReconstruction/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download tomo-em 
Selected datasets: tomo-em
Local copy of dataset tomo-em detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomogramReconstruction" "Runs/000002_ProtImportTs/logs/run.db" 2'

 ------------------- Test tomo3D reconstruction with SIRT-------------------
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomogramReconstruction" "Runs/000084_ProtJjsoftReconstructTomogram/logs/run.db" 84'
[   FAILED ] TestTomogramReconstruction.testReconstructionSIRT


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_reconstruct_tomogram.py", line 95, in testReconstructionSIRT
    self._checkResults(setOfReconstructedTomograms)
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_reconstruct_tomogram.py", line 111, in _checkResults
    self.assertEqual(tomo.getTsId(), testTsIds[i])
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'a' != 'b'
- a
+ b



 -------------------- Test tomo3D reconstruction with WBP-------------------
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomogramReconstruction" "Runs/000149_ProtJjsoftReconstructTomogram/logs/run.db" 149'
[   FAILED ] TestTomogramReconstruction.testReconstructionWBP


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_reconstruct_tomogram.py", line 81, in testReconstructionWBP
    self._checkResults(setOfReconstructedTomograms)
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_reconstruct_tomogram.py", line 111, in _checkResults
    self.assertEqual(tomo.getTsId(), testTsIds[i])
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'a' != 'b'
- a
+ b



[==========] run 2 tests (29.933 secs)

[  FAILED  ] 2 tests

[  PASSED  ] 0 tests

```

One test here fail, it seems that some attribute has changed:
```

(base) harastamadm@PC4-0002-D:/shared/scipion3/software/em/tomo3d-22.01.27$ scipion3 tests tomo3d.tests.test_protocol_alignts
Scipion v3.0.12 - Eugenius
Running tests....
Creating project at /media/SharedDisk/ScipionProjects/projects/TestAlignTs/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download tomo-em 
Selected datasets: tomo-em
Local copy of dataset tomo-em detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestAlignTs" "Runs/000002_ProtImportTs/logs/run.db" 2'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestAlignTs" "Runs/000084_ProtImodXcorrPrealignment/logs/run.db" 84'
[   FAILED ] TestAlignTs.setUpClass


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_alignts.py", line 48, in setUpClass
    cls.setOfXcorrTs = cls._runXcorrPrealignment()
  File "/shared/scipion3/plugins/scipion-em-tomo3d/tomo3d/tests/test_protocol_alignts.py", line 80, in _runXcorrPrealignment
    return protXcorr.outputSetOfTiltSeries
AttributeError: 'ProtImodXcorrPrealignment' object has no attribute 'outputSetOfTiltSeries'


[==========] run 0 tests (17.450 secs)

[  FAILED  ] 1 tests

[  PASSED  ] -1 tests



```

**Comment by JorMaister** [comment]
Thanks for reporting!
They pass after the last update. Are they passing to you, @MohamadHarastani?

**Comment by MohamadHarastani** [comment]
Thanks Jorge! 
I will be able to test next week. If the tests don't pass I will reopen the issue.
Cheers
Mohamad
